// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: order_status_changed_event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_CANCELED    OrderStatus = 3
	OrderStatus_ORDER_STATUS_ASSEMBLING  OrderStatus = 4
	OrderStatus_ORDER_STATUS_ASSEMBLED   OrderStatus = 5
	OrderStatus_ORDER_STATUS_DELIVERING  OrderStatus = 6
	OrderStatus_ORDER_STATUS_ISSUED      OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_CANCELED",
		4: "ORDER_STATUS_ASSEMBLING",
		5: "ORDER_STATUS_ASSEMBLED",
		6: "ORDER_STATUS_DELIVERING",
		7: "ORDER_STATUS_ISSUED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_CANCELED":    3,
		"ORDER_STATUS_ASSEMBLING":  4,
		"ORDER_STATUS_ASSEMBLED":   5,
		"ORDER_STATUS_DELIVERING":  6,
		"ORDER_STATUS_ISSUED":      7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_status_changed_event_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_status_changed_event_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_status_changed_event_proto_rawDescGZIP(), []int{0}
}

type OrderStatusChangedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MessageId          string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	OrderId            string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status             OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	CancellationReason *string                `protobuf:"bytes,5,opt,name=cancellation_reason,json=cancellationReason,proto3,oneof" json:"cancellation_reason,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderStatusChangedEvent) Reset() {
	*x = OrderStatusChangedEvent{}
	mi := &file_order_status_changed_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusChangedEvent) ProtoMessage() {}

func (x *OrderStatusChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_changed_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusChangedEvent.ProtoReflect.Descriptor instead.
func (*OrderStatusChangedEvent) Descriptor() ([]byte, []int) {
	return file_order_status_changed_event_proto_rawDescGZIP(), []int{0}
}

func (x *OrderStatusChangedEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderStatusChangedEvent) GetCancellationReason() string {
	if x != nil && x.CancellationReason != nil {
		return *x.CancellationReason
	}
	return ""
}

func (x *OrderStatusChangedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_order_status_changed_event_proto protoreflect.FileDescriptor

const file_order_status_changed_event_proto_rawDesc = "" +
	"\n" +
	" order_status_changed_event.proto\x12\x06orders\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x02\n" +
	"\x17OrderStatusChangedEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x124\n" +
	"\x13cancellation_reason\x18\x05 \x01(\tH\x00R\x12cancellationReason\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x16\n" +
	"\x14_cancellation_reason*\xe6\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x03\x12\x1b\n" +
	"\x17ORDER_STATUS_ASSEMBLING\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_ASSEMBLED\x10\x05\x12\x1b\n" +
	"\x17ORDER_STATUS_DELIVERING\x10\x06\x12\x17\n" +
	"\x13ORDER_STATUS_ISSUED\x10\aBPZNorder-notification-service/internal/transport/proto/order_status_changed;protob\x06proto3"

var (
	file_order_status_changed_event_proto_rawDescOnce sync.Once
	file_order_status_changed_event_proto_rawDescData []byte
)

func file_order_status_changed_event_proto_rawDescGZIP() []byte {
	file_order_status_changed_event_proto_rawDescOnce.Do(func() {
		file_order_status_changed_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_status_changed_event_proto_rawDesc), len(file_order_status_changed_event_proto_rawDesc)))
	})
	return file_order_status_changed_event_proto_rawDescData
}

var file_order_status_changed_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_status_changed_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_status_changed_event_proto_goTypes = []any{
	(OrderStatus)(0),                // 0: orders.OrderStatus
	(*OrderStatusChangedEvent)(nil), // 1: orders.OrderStatusChangedEvent
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_order_status_changed_event_proto_depIdxs = []int32{
	0, // 0: orders.OrderStatusChangedEvent.status:type_name -> orders.OrderStatus
	2, // 1: orders.OrderStatusChangedEvent.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_status_changed_event_proto_init() }
func file_order_status_changed_event_proto_init() {
	if File_order_status_changed_event_proto != nil {
		return
	}
	file_order_status_changed_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_status_changed_event_proto_rawDesc), len(file_order_status_changed_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_status_changed_event_proto_goTypes,
		DependencyIndexes: file_order_status_changed_event_proto_depIdxs,
		EnumInfos:         file_order_status_changed_event_proto_enumTypes,
		MessageInfos:      file_order_status_changed_event_proto_msgTypes,
	}.Build()
	File_order_status_changed_event_proto = out.File
	file_order_status_changed_event_proto_goTypes = nil
	file_order_status_changed_event_proto_depIdxs = nil
}
